TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Models/Utente.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Back_End_GYM.Models {
    public class Utente
    {
        //DATI UTENTE 

        [BsonElement("utenteId")]
        public ObjectId Id { get; set; }

        [BsonElement("nome")]
        [Required(ErrorMessage = "Il campo Nome è obbligatorio")]
        [MaxLength(100)]
        public string Nome { get; set; }
        
        [BsonElement("cognome")]
        [Required(ErrorMessage = "Il campo Cognome è obbligatorio")]
        [MaxLength(100)]
        public string Cognome { get; set; }
        
        [BsonElement("indirizzo")]
        [MaxLength(100)]
        public string Indirizzo { get; set; }

        [BsonElement("dataNascita")]
        [BsonDateTimeOptions(DateOnly = true)]
        [MaxLength(100)]
        private DateTime dataNascita;

        [BsonIgnore]
        public DateTime DataNascita
        {
            get { return dataNascita; }
            set { dataNascita = (DateTime)value; }
        }

        //Controllo email----------------------------------------------------------
        [BsonElement("email")]
        [Required(ErrorMessage = "Il campo Email è obbligatorio")]
        [RegularExpression(@"^[^@\s] +@[^@\s]+\.[^@\s]+$", ErrorMessage = "L'Email deve rispettare il formato corretto")]
        [MaxLength(100)]
        public string Email { get; set; }

        //Controllo password----------------------------------------------------------
        [BsonElement("password")]
        [Required(ErrorMessage = "La password deve essere lunga minimo 6 caratteri")]
        [MaxLength(100),MinLength(6)]
        public string Password { get; set; }

        [BsonIgnore]
        private List<Iscrizione> elencoIscrizioni = new List<Iscrizione>();
        [BsonIgnore]
        public List<Iscrizione> ElencoIscrizioni
        {
            get { return elencoIscrizioni; }
            set { elencoIscrizioni = value; }
        }

}
}

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Controllers/UtenteController.cs
using Back_End_GYM.Data;
using Back_End_GYM.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MongoDB.Bson;
using MySqlX.XDevAPI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Back_End_GYM.Controllers
{
    public class UtenteController : Controller {
        private UtenteRepo _repoUtente;
        private CorsoRepo _repoCorso;
        private IscrizioneRepo _repoIscrizione;

        public UtenteController(IConfiguration config) {
            if (_repoUtente == null) {
                bool isOnline = config.GetValue<bool>("IsOnline");

                string connString = isOnline ?
                    config.GetValue<string>("MongoDbSettings:OnlineDb") :
                    config.GetValue<string>("MongoDbSettings:LocalDb");

                string dbString = config.GetValue<string>("MongoDbSettings:NomeDb");

                _repoUtente = new UtenteRepo(connString, dbString);
                _repoCorso = new CorsoRepo(connString, dbString);
                _repoIscrizione = new IscrizioneRepo(connString, dbString);
            }
        }
        public IActionResult Login() {
            return View();
        }

        public RedirectResult LoginCheck(Utente objUtente) {
            Utente loginAttempt = _repoUtente.GetByEmail(objUtente.Email);
            if (loginAttempt != null && loginAttempt.Password == objUtente.Password) {
                HttpContext.Session.SetString("isLogged", loginAttempt.Email);

                return Redirect("/Utente/MyCourses");
            }
            else {
                return Redirect("/Utente/Login");
            }
        }

        public IActionResult SignUp() {
            return View();
        }

        public IActionResult SignedIn() {
            return View();
        }

        [HttpPost]
        public RedirectResult SignUpCheck(Utente objUtente) {
            if (_repoUtente.Insert(objUtente)) {
                return Redirect("/Utente/SignedIn");
            }
            return Redirect("/Utente/SignUp");

        }
        public IActionResult Courses() {
            return View(_repoCorso.GetAll().ToList());
        }

        public IActionResult IscrizioneCorso(string codice) {
            ObjectId idCorso = _repoCorso.GetByCodice(codice).Id;
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null) {
               
                Utente temp = _repoUtente.GetByEmail(currentUser);

                
                if (_repoIscrizione.GetAll().Where(i => i.UtenteId == temp.Id) == null) {
                    
                    Iscrizione newSub = new Iscrizione() {
                        CorsoId = idCorso,
                        UtenteId = temp.Id,
                        IscrizioneId = new ObjectId(),
                        DataIscrizione = DateTime.Now,
                        CorsoRIF = _repoCorso.GetById(idCorso),
                        UtenteRIF = temp
                    };
                    temp.ElencoIscrizioni.Add(newSub);
                    _repoIscrizione.Insert(newSub);
                    return Redirect("/Utente/MyCourses");
                }
                else {
                    var findCorso = _repoIscrizione.GetAll()
                        .Where(i => i.CorsoId == idCorso)
                        .Where(i => i.UtenteId == temp.Id)
                        .FirstOrDefault();
                    
                    if (findCorso == null) {
                       
                        Iscrizione newSub = new Iscrizione() {
                            CorsoId = idCorso,
                            UtenteId = temp.Id,
                            IscrizioneId = new ObjectId(),
                            DataIscrizione = DateTime.Now,
                            CorsoRIF = _repoCorso.GetById(idCorso),
                            UtenteRIF = temp
                        };
                        temp.ElencoIscrizioni.Add(newSub);
                        _repoIscrizione.Insert(newSub);
                        return Redirect("/Utente/MyCourses");
                    }
                    //L'utente è già iscritto al corso
                    else
                        return Redirect("/Utente/MyCourses");
                }
            }
            return Redirect("/Utente/Courses");
        }

        //Accesso corsi loggato-----
        public IActionResult MyCourses() {
           string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null) {
                Utente temp = _repoUtente.GetByEmail(currentUser);
                List<Corso> elencoCorsi = _repoIscrizione.GetAll()
                    .Where(i => i.UtenteId == temp.Id)
                    .Select(i => _repoCorso.GetById(i.CorsoId)).ToList();


                return View(elencoCorsi);
            }
            return Redirect("/Utente/Login");
        }

        public RedirectResult Disiscriviti(string codice) {
            ObjectId idCorso = _repoCorso.GetByCodice(codice).Id;
            string currentUser = HttpContext.Session.GetString("isLogged");
            if (currentUser != null) {
                Utente temp = _repoUtente.GetByEmail(currentUser);
                Iscrizione queryIscrizione = _repoIscrizione.GetAll()
                    .Where(i => i.CorsoId == idCorso)
                    .Where(i => i.UtenteId == temp.Id)
                    .FirstOrDefault();
                if (_repoIscrizione.Delete(queryIscrizione.IscrizioneId)) {
                    temp.ElencoIscrizioni.Remove(queryIscrizione);
                    return Redirect("/Utente/MyCourses");
                }
            }
            return Redirect("/Utente/Courses");
        }
    }
}

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Views/Utente/Courses.cshtml
@model List<Back_End_GYM.Models.Corso>
@{ Layout = "_Layout"; 
}

<table class="table borders rounded table-striped table-hover">
    <thead class="thead-dark">
    <th>Titolo</th>
    <th >Descrizione</th>
    <th>Codice</th>
    <th>Data</th>
    <th>Ora</th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var item in Model) {
<tr>
    <td>@item.Titolo</td>
    <td>@item.Descrizione</td>
    <td>@item.Codice</td>
    <td>@item.DataOra.ToLongDateString()</td>
    <td>@item.DataOra.ToShortTimeString()</td>
    <td><a class="btn btn-info" asp-controller="Utente" asp-action="IscrizioneCorso" asp-route-codice="@item.Codice">Iscrivimi</a></td>
</tr>}
    </tbody>
</table>

@*<div class="alert alert-success" role="alert">
        This is a success alert—check it out!
    </div>*@

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Views/Utente/Login.cshtml
@model Back_End_GYM.Models.Utente

@{ Layout = "_Layout";
   ViewBag.Title = "Login"; }

<!-- CSS -->
<div class="container-fluid">
    <style>
        body {
            background-color: #282828;
        }


        .container {
            background-color: white;
            padding: 50px;
        }

        #title {
            font-family: 'Lobster', cursive;
            ;
        }
    </style>

    <!-- Form Login -->


    <h2 class="text-center" id="title">Modulo di Accesso</h2>
    <div class="col-md-5">
        <form asp-controller="Utente" asp-action="LoginCheck" method="post" class="form-group">
            <fieldset>
                <div class="form-group">
                    <label asp-for="Email">Email</label>
                    <input type="text" asp-for="Email" id="logEmail" class="form-control" placeholder="Email" />
                    <label asp-for="Password" class="mt-1">Password</label>
                    <input type="password" asp-for="Password" id="logPassword" class="form-control" placeholder="Password" />
                    <button type="submit" class="btn btn-dark mt-2">LogIn</button>
                </div>
                <small>Non hai un'account? <a href="/Utente/SignUp">Registrati!</a></small>
            </fieldset>
        </form>
    </div>
   

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Views/Utente/MyCourses.cshtml
@model List<Back_End_GYM.Models.Corso>
@{
    Layout = "_Layout";
}


<table class="table borders rounded table-striped table-hover">
    <thead class="thead-dark">
    <th>Titolo</th>
    <th>Descrizione</th>
    <th>Codice</th>
    <th>Data</th>
    <th>Ora</th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var item in Model) {
<tr>
    <td>@item.Titolo</td>
    <td>@item.Descrizione</td>
    <td>@item.Codice</td>
    <td>@item.DataOra.ToLongDateString()</td>
    <td>@item.DataOra.ToShortTimeString()</td>
    <td><a class="btn btn-danger" asp-controller="Utente" asp-action="Disiscriviti" asp-route-codice="@item.Codice"><i class="fa-solid fa-trash"></i>Disiscriviti</a></td>
</tr>
}
    </tbody>
</table>

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Views/Utente/SignUp.cshtml
@model Back_End_GYM.Models.Utente

@{ Layout = "_Layout"; }

<!-- CSS -->
<div class="container-fluid">
    <style>
        body {
            background-color: #282828;
        }

        .container {
            background-color: white;
            padding: 50px;
        }

        #title {
            font-family: 'Lobster', cursive;
            ;
        }
    </style>

    <!-- Form Sing-Up -->

        <h2 class="text-center" id="title">Modulo Registrazione</h2>
        <hr>
        <div class="row">
            <div class="col-md-5">
                <form role="form" asp-controller="Utente" asp-action="SignUpCheck" method="post">
                    <fieldset>
                        <p class="text-uppercase pull-center"> Registrati:</p>
                        NOME 
                        <div class="form-group">
                            <input type="text" asp-for="Nome" id="inNome" class="form-control" placeholder="Inserisci Nome">
                        </div>
                        COGNOME
                        <div class="form-group">
                            <input type="text" asp-for="Cognome" id="inCognome" class="form-control " placeholder="Inserisci Cognome">
                        </div>
                        INDIRIZZO
                        <div class="form-group">
                            <input type="text" asp-for="Indirizzo" id="inIndirizzo" class="form-control " placeholder="Inserisci il tuo indirizzo">
                        </div>
                        E-MAIL 
                        <div class="form-group">
                            <input asp-for="Email" id="inEmail" class="form-control input-lg" placeholder="Email">
                        </div>
                        DATA NASCITA 
                        <div class="form-group">
                            <input type="date" asp-for="DataNascita" id="inData" class="form-control " placeholder="Data Di Nascita">
                        </div>

                        <div class="form-group">
                            <input asp-for="Password" type="password" id="inPassword" class="form-control " placeholder="Inserisci Password">
                        </div>

                        <div>
                            <input type="submit" class="btn btn-lg btn-primary" value="Register">
                        </div>

                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input">
                                By Clicking register you're agree to our policy & terms
                            </label>
                        </div>


                    </fieldset>
                </form>
            </div>
        </div>
 

TASK_GESTIONE _PALESTRA_Video/Razor/Back_End_GYM/Back_End_GYM/Views/Utente/SignedIn.cshtml
@model Back_End_GYM.Models.Utente

@{ Layout = "_Layout";

   ViewBag.Title = "Registrazione avvenuta con successo!"; 
 
 }
<div class="row">
    <div class="col"></div>
    <div class="col text-center .btn ">
        <h2>Registrazione avvenuta con successo!</h2>
        <h4>Premi ok per tornare alla home</h4>
        <a class="btn btn-primary" asp-controller="Utente" asp-action="Login">Ok</a>
    </div>
    <div class="col"></div>
</div>